---
resources:
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - route.yaml

# Namespace not specified - deploy with: oc apply -k obs/experimental/llama-stack-playground -n <your-namespace>